// <auto-generated />
using System;
using Back_EndTest.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Back_EndTest.Migrations
{
    [DbContext(typeof(TestDbContext))]
    [Migration("20210611001924_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Back_EndTest.Models.Status", b =>
                {
                    b.Property<int>("id_status")
                        .HasColumnType("int")
                        .HasColumnName("id_status");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("status");

                    b.HasKey("id_status")
                        .HasName("PrimaryKey_id_status");

                    b.ToTable("status");

                    b.HasData(
                        new
                        {
                            id_status = 0,
                            status = "Abierto"
                        },
                        new
                        {
                            id_status = 1,
                            status = "Cerrado"
                        });
                });

            modelBuilder.Entity("Back_EndTest.Models.Ticket", b =>
                {
                    b.Property<int>("id_ticket")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_ticket")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("creation_date")
                        .HasColumnType("datetime")
                        .HasColumnName("creation_date");

                    b.Property<int>("id_status_fk")
                        .HasColumnType("int")
                        .HasColumnName("id_status_fk");

                    b.Property<string>("user")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("user");

                    b.HasKey("id_ticket")
                        .HasName("PrimaryKey_id_ticket");

                    b.HasIndex("id_status_fk");

                    b.ToTable("ticket");
                });

            modelBuilder.Entity("Back_EndTest.Models.Ticket", b =>
                {
                    b.HasOne("Back_EndTest.Models.Status", "status")
                        .WithMany("Tickets")
                        .HasForeignKey("id_status_fk")
                        .HasConstraintName("status_ibfk_1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("status");
                });

            modelBuilder.Entity("Back_EndTest.Models.Status", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
